<a href="https://colab.research.google.com/github/divsal009/div/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3])

In [ ]:
print(x)

[1 2 3]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
x=np.array([[1,2,3],[9,8,7]])

In [ ]:
print(x)

[[1 2 3]
 [9 8 7]]


In [ ]:
np.array([1+2j, 3, 5+6*1j])

array([1.+2.j, 3.+0.j, 5.+6.j])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,3,.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.linspace(1,6,6)

array([1., 2., 3., 4., 5., 6.])

In [ ]:
np.linspace(1,6,3)

array([1. , 3.5, 6. ])

In [ ]:
np.random.random((2,3))

array([[0.36699048, 0.98327196, 0.84645793],
       [0.49148607, 0.45963953, 0.17866338]])

In [ ]:
a=np.arange(3)
print(a)


[0 1 2]


In [ ]:
b=np.arange(9).reshape(3,3)

In [ ]:
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
b=np.arange(9).reshape(3,2,2)

ValueError: ignored

In [ ]:
x=np.arange(1,26).reshape(5,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(x[1:4,:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print(x[:,1:3])

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]


In [ ]:
print(x[1:3,2:4])

[[ 8  9]
 [13 14]]


In [ ]:
print(x[0:5:2,:])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [ ]:
print(x[2:5:2,1:4:2])

[[12 14]
 [22 24]]


In [ ]:
print(x[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [ ]:
print(x[:,:-2])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]


In [ ]:
a=np.arange(4).reshape(2,2)
b=np.arange(4).reshape(2,2)

In [ ]:
print(a+b)

[[0 2]
 [4 6]]


In [ ]:
print(a**2)

[[0 1]
 [4 9]]


In [ ]:
print(np.dot(a,b))

[[ 2  3]
 [ 6 11]]


In [ ]:
print((a*b))

[[0 1]
 [4 9]]


In [ ]:
print(a.ravel())

[0 1 2 3]
