<a href="https://colab.research.google.com/github/divsal009/div/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor is mathematical representation of scalar,vector, matrixof N-D & rank

In [1]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.2.0


**constant**

In [4]:
tf.constant(2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**vectorrepresentation**

In [8]:
tf.constant([1,2,3,4,5])

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [9]:
tf.constant([1,2,3,4,5],dtype='int8')

<tf.Tensor: shape=(5,), dtype=int8, numpy=array([1, 2, 3, 4, 5], dtype=int8)>

In [11]:
const_1 = tf.constant([1,2,3,4,5,6], dtype='int8')


In [12]:
const_1.numpy()


array([1, 2, 3, 4, 5, 6], dtype=int8)

In [13]:
const_1.shape


TensorShape([6])

In [17]:
#matrix
tf.constant([[1,2,3],[4,5,6],[7,8,9],[9,0,9]])

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 0, 9]], dtype=int32)>

In [19]:
tf.constant([[[5, 7, 10],
             [10, 11, 12],
             [22, 23, 24]],
            [[15, 17, 20],
             [21, 15, 22],
             [22, 25, 34]]])

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 5,  7, 10],
        [10, 11, 12],
        [22, 23, 24]],

       [[15, 17, 20],
        [21, 15, 22],
        [22, 25, 34]]], dtype=int32)>

**variable datatype**

In [25]:
var_1 = tf.Variable(100 , dtype = 'float16')


In [26]:
var_1.numpy()

100.0

In [28]:
var_2 = tf.Variable([1,2,3,4,5 ], dtype = 'float16')


In [29]:
var_2.numpy()

array([1., 2., 3., 4., 5.], dtype=float16)

In [31]:
var_3 = tf.Variable([1,2,3,4,5 ])

In [32]:
var_3.numpy()

array([1, 2, 3, 4, 5], dtype=int32)

In [33]:
 tf.Variable([1,2,3,4,5 ]).shape

TensorShape([5])

mathematical representation

In [38]:
x=tf.constant([[3,4]])

In [39]:
x

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[3, 4]], dtype=int32)>

In [40]:
weights=tf.Variable([[2],
                    [4]]
                    )

In [41]:
tf.matmul(weights,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [12, 16]], dtype=int32)>

In [42]:
tf.matmul(weights,x).numpy()

array([[ 6,  8],
       [12, 16]], dtype=int32)