<a href="https://colab.research.google.com/github/divsal009/div/blob/master/Tensorflow_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
rank_1_tensor = tf.constant([2,3,4])
print(rank_1_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [8]:
rank_2_tensor = tf.constant([[2.6,3,4],[1,2,1],[5,6,7]])
print(rank_2_tensor)

tf.Tensor(
[[2.6 3.  4. ]
 [1.  2.  1. ]
 [5.  6.  7. ]], shape=(3, 3), dtype=float32)


In [7]:
rank_2_tensor = tf.constant([[2,3,4],[1,2,1],[5,6,7]],dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[2. 3. 4.]
 [1. 2. 1.]
 [5. 6. 7.]], shape=(3, 3), dtype=float16)


In [12]:
my_variable=tf.Variable([5+4j,6+1j])
print(my_variable)

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>
